# Generated by Django 4.0.3 on 2022-04-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('username', models.TextField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
